### ISSUE TITLE
Deploy older Solr versions

### ISSUE THREAD

**Issue by icyd** [apache/solr-operator#167]
Is it possible to generate/deploy older versions of Solr with this operator (ie 5.5.x)? Or there are dependencies related with the version? Thanks!

**Comment by HoustonPutman** [comment]
It might be possible? I know I have never tested below a 7.x version.

The only issues would be `bin/solr` envVars and commands, the Collections API compatibility, and possibly the Solr XML. My advice would be to try it and see if it works. If you can start a Solr cloud, that is a good start. The next thing I would test would be a rolling restart, since that is the only API command that the SolrCloud controller utilizes. The SolrCollection/SolrBackup/SolrCollectionAliases will have other API compatibility concerns.

The SolrPrometheusExporter will 100% not work, because that was introduced in 7.0 I believe.

In the future we do plan on using newer Solr features, and limiting the version compatibility because of that. However that is not on the roadmap yet, and won't be for a while.
