### ISSUE TITLE
How to specify which PVC to use

### ISSUE THREAD

**Issue by gthvidsten** [apache/solr-operator#378]
I need the Solr Operator (and Zookeeper Operator) to have persistent storage so that the server can be brought down/up without any data loss. I found the `SolrCloud.spec.dataStorage.persistent` setting [here](https://apache.github.io/solr-operator/docs/solr-cloud/solr-cloud-crd.html) but I can't find how to specify which Persistent Volume Claim to use for this, or alternatively which Storage Class to use.

How can I have the Solr Operator use a specific PVC or StorageClass for persistent storage?
Similarily, how can I do the same for Zookeeper?

**Comment by gthvidsten** [comment]
I may have figured it out. The following command is used to install the Solr Cloud:

```
helm install example-solr apache-solr/solr --version 0.5.0 \
--set image.tag=8.4 \
--set dataStorage.persistent.pvc.storageClassName="solr-storage" \
--set zk.provided.persistence.spec.storageClassName="solr-storage"
```
Where `solr-storage` is an existing and functional StorageClass.

It would be nice if someone could confirm that this is correct and I'm not missing anything (and that default values for the rest of the settings are good enough)

**Comment by HoustonPutman** [comment]
That is correct! I think with the Solr helm chart, you also need to include `--set dataStorage.type=persistent`, since the default is ephemeral.

And as per the original question, you cannot use existing PVCs with a SolrCloud for data storage, since behind the scene it creates a StatefulSet, which it turn creates new individual PVCs for each SolrCloud pod.

**Comment by gthvidsten** [comment]
I believe everything was answered here, so closing this
