### ISSUE TITLE
Can not use the collections API to backup to S3

### ISSUE THREAD

**Issue by echarles** [apache/solr-operator#404]
Hi, I have a running solrcloud on my EKS cluster and can successfully use `SolrBackup` to create backups to a S3 bucket. As `solr-cloud` does not (yet) ship out-of-the-box solution to restore from a backup, I have tried to use the core Solr Collections API documented on https://solr.apache.org/guide/8_11/collection-management.html#restore. This throws a error `msg":"specified location s3://my-bucket does not exist`...

To understand if the issue was due an incompatiblity e.g. on format, folder... I have tried to use the core Solr Collection API to create a backup to S3 https://solr.apache.org/guide/8_11/collection-management.html#backup and https://solr.apache.org/guide/8_11/making-and-restoring-backups.html#s3backuprepository with the following request.

```bash
curl http://localhost:8983/solr/admin/collections -d '
action=BACKUP&
repository=s3-bu&
collection=backups&
location=s3://datalayer-backups&
name=backup-dir'
```

This results in the following error

```
{
  "responseHeader":{
    "status":500,
    "QTime":59},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"specified location s3://my-bucket/ does not exist.",
    "trace":"org.apache.solr.common.SolrException: specified location s3://my-bucket/ does not exist.\n\tat org.apache.solr.handler.admin.CollectionsHandler$CollectionOperation.lambda$static$33(CollectionsHandler.java:1134)\n\tat org.apache.solr.handler.admin.CollectionsHandler$CollectionOperation.execute(CollectionsHandler.java:1453)\n\tat org.apache.solr.handler.admin.CollectionsHandler.invokeAction(Col
```

I have precreated the `backup-id` in my S3 bucket, tried various format for the collection (removed `s3://` prefix) without luck.

Are my parameters wrong, do I have an issues with my env (env works with `SolrBackup` and K8ssandra backup/restore) or is there a issue to fix in the source code?

Thx!

**Comment by echarles** [comment]
I have tested on my laptop with a local and receive the same error. This is thus not related to the operator. I let this open a bit before closing.

**Comment by echarles** [comment]
There is a very recent thread on the solr mailing list on that exactly https://lists.apache.org/list?users@solr.apache.org:lte=1M:S3%20backup

I am unblocked, closing.

**Comment by Himanshusoni9** [comment]
One More issue : On  Solr Collection Data Backup Based on Condition/Data Filter.(There is no provision for that . )

Because SOLR BACKUP API with Query is not working
//http://localhost:8983/solr/admin/collections?action=RESTORE&name=myBackupName&location=C:\Users\DELL\Downloads\SOLR_BACKUP&collection=myCondCollection&query=text:cellphone

I am trying out to perform backups of our Solr data with a particular condition in mind.

To provide some context, let's say Solr collection consists of 100 records, among which 70 records contain the text "mobile," and the remaining 30 records contain the text "cellphone." my objective is to take a Solr collection/data backup that contains only the records the text "cellphone" – essentially, we want to create a backup file that reflects these 30 specific records only.

I would greatly appreciate it if you could share insights on the best practices or methods to achieve this selective backup based on a condition. If there are specific parameters or commands we should be utilizing, kindly provide the necessary guidance. Additionally, any documentation or references you could point us to would be immensely helpful.

Thank you in advance for your time and assistance. We value your expertise and look forward to implementing an efficient solution based on your recommendations.

**Comment by HoustonPutman** [comment]
This is a new feature, as Solr does not support this (and is unrelated to the Solr Operator). Please use the [Solr Users Mailing list](https://solr.apache.org/community.html#mailing-lists-chat) to ask this question.
