### ISSUE TITLE
Possibility to run as readOnlyRootFilesysystem

### ISSUE THREAD

**Issue by thomaswoeckinger** [apache/solr-operator#624]
In Openshift environments (may in others too) it is possible to restrict containers with SecurityContextConstraints (SCC).

Especial setting the root filesystem to read only would increase security.

Currently the init container `setup-zk`? is preventing read only root filesystem, as it is writing  to `/tmp`.

So if this container would mount an `emptyDir` to /tmp it would be possible to set the root filesystem to read only.

**Comment by thomaswoeckinger** [comment]
It is not that complicated, it is sufficient to use an emptyDir and mount it to /tmp. This is because readOnlyRootFilesystem is not used wirh mount points.

**Comment by HoustonPutman** [comment]
Yeah @radu-gheorghe , Thomas is not saying that we need to be able to specify `readOnlyFilesystem`, as that is already possible. We just need to make sure any folder that we write to in Solr or in the init containers is backed by a volume (ephemeral volumes by default), so that we don't see an error when the `readOnlyFilesystem` option is used.

**Comment by radu-gheorghe** [comment]
OK, so I'll change `zk-init` to mount an `emptyDir` into `/tmp`. I'll also add `readOnlyFilesystem` to its definition in order to test it, but I'd like to leave it like that, I don't see a reason not to. Sounds good?

And I'll also try to test with `readOnlyFilesystem` everywhere. Maybe the Solr container also writes to `/tmp` or somewhere funky. I couldn't do that so far, but I'll press on 😁
