### ISSUE TITLE
Pods begin to restart as soon auth is enabled

### ISSUE THREAD

**Issue by VishwajeetPandeyy** [apache/solr-operator#730]
As soon as I enable authentication using the command:

`bin/solr auth enable -credentials admin:admin -type basicAuth -z "$ZK_HOST"`

the Solr pods begin to restart. 
However, when authentication is disabled, they stabilize and function normally. 
Does basic authentication now require configuration exclusively via `security.json` instead of using the above command?

@HoustonPutman

**Comment by janhoy** [comment]
You should provision auth using the operator's configuration, not manually. The operator needs to know the basic auth password so it can execute the startup- and liveness-probes. Or you can flip the probes to instead execute CLI commands, but it is heavier. Or lastly you can setup your authz so that the health and clusterstate endpoints are unauthenticated.

**Comment by gerlowskija** [comment]
Hi @VishwajeetPandeyy - for error messages like "Underlying core creation failed while creating collection", you're likely to find more useful information in Solr's logs.

The "AUTOCREATED" config name suffix is expected behavior of Solr's.  I'm a bit hazy on the context, but I think the intention is that creating a copy of the configset is preferred in some scenarios to protect users from unknowingly modifying a config that may be used by multiple collections.  See the [collection-creation docs here](https://solr.apache.org/guide/solr/latest/deployment-guide/collection-management.html#create-parameters) for more details.

In general - these sort of questions are better suited for Solr's user mailing list: users@solr.apache.org.  Please raise similar questions there going forward!
